---
- name: Ansible home-ops
  hosts: all
  # become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
      tags:
        - pip
      become: true

    - role: geerlingguy.docker
      tags:
        - docker
      become: true

  tasks:
    - name: Deploy swarm
      ansible.builtin.import_tasks: tasks/swarm.yml
      tags:
        - swarm

  # tasks:
  #   - name: Configure general settings
  #     ansible.builtin.include_role:
  #       name: general

  #   - name: Install cloudflared
  #     ansible.builtin.include_role:
  #       name: cloudflared
  #     when: cloudflared_enabled is defined and cloudflared_enabled

  #   - name: Install wakapi
  #     ansible.builtin.include_role:
  #       name: wakapi
  #     when: wakapi_enabled is defined and wakapi_enabled

  #   - name: Install siyuan
  #     ansible.builtin.include_role:
  #       name: siyuan
  #     when: siyuan_enabled is defined and siyuan_enabled
